[project]
name = "user_resources_misc"
version = "0.1"
requires-python = ">=3.12"

[project.scripts]
unity-disk-usage = "user_resources_misc.unity_disk_usage:main"
unity-disk-usage-peruser = "user_resources_misc.unity_disk_usage_per_user:main"
